### ISSUE TITLE
Move project to organization lcdproc

### ISSUE THREAD

**Issue by antoneliasson** [boncey/lcdjava#3]
I'm back!

I have started thinking about making stable releases of LCDjava and eventually submitting it to the central Maven repository, so that projects can easily use it simply by declaring a dependency, without having to manually juggle JAR files.

That means that LCDjava needs a good and stable groupId and artifactId. These are also part of the Java package that LCDjava's classes are filed under. It makes sense to me to place it under org.lcdproc.lcdjava, if the LCDproc crew agrees to this. Now that LCDproc is moving to Github LCDjava could also move to their organization (https://github.com/lcdproc) to reflect the potential new groupId. I'll ask about both issues on their mailing list. Do you have any objections to this?

**Comment by boncey** [comment]
No, sounds like a great idea!

**Comment by antoneliasson** [comment]
Hi again! Willfe at lcdproc is positive to the adoption of lcdjava. Now we need your help. As soon as willfe has removed https://github.com/lcdproc/lcdjava, could you go to the Settings tab of this repository and down in the Danger Zone do a transfer of lcdjava to the organization lcdproc? When he accepts the transfer you'll be automatically added as a collaborator in the new repository.

**Comment by boncey** [comment]
Hi, sounds good.
The `lcdjava` repo is still there now so I'll try again later.
Nudge me on this thread if you do see that it's been deleted please.

**Comment by antoneliasson** [comment]
_nudge_ Try it now.

**Comment by boncey** [comment]
Just tried and it failed saying `You don’t have admin rights to lcdproc`.
I guess I will need that (if only temporarily).

**Comment by antoneliasson** [comment]
I asked, and @willfe declined (understandably). He suggested the workaround of first transferring the repo to his personal account, and then he will transfer it to the lcdproc organization (which he is the owner of). Could you do that?

**Comment by boncey** [comment]
OK, have done that, it's now showing as `Repository transfer to willfe requested`.
Let's hope it works.

**Comment by willfe** [comment]
Looks like we're golden! I received the transfer, and then transferred this repo to the LCDproc organization, so it should be live now at https://github.com/lcdproc/lcdjava. Let me know if there are any missing settings or memberships. I'll leave this open for now just in case :)

BTW, welcome to the project! Glad to have you join us!

**Comment by boncey** [comment]
Hooray!
Great that we got there in the end.

GitHub redirects from the old project URL work too which is good.

**Comment by antoneliasson** [comment]
Excellent! Thanks for the warm welcome and thanks to both of you for your help!

There is also a friend repository on my profile containing demo projects at https://github.com/antoneliasson/lcdjava-demos . I opted to keep these projects in a separate repo (initially they were even two separate repositories) to show not only how to use the LCDjava API, but also how to integrate the library in a larger project for those who do not speak pom.xml fluently. Should we move these to the lcdproc organization using the same procedure?

**Comment by willfe** [comment]
Sure! Send it along and I'll get it moved to the org.

**Comment by willfe** [comment]
https://github.com/lcdproc/lcdjava-demos -- looks like we're live!

Sanity checks are welcome. If you're satisfied that the moves have been successful, we can close this issue (and the related one on the LCDproc project).

**Comment by antoneliasson** [comment]
Looks great from here! I can push and pull both repositories. Closing.
