### ISSUE TITLE
Missing Licensing Info

### ISSUE THREAD

**Issue by manitou2k** [boncey/lcdjava#5]
I can't find any licensing information on the lcdjava library.  Could you please let me know if this can be used under something like the MIT license in a commercial product?

**Comment by antoneliasson** [comment]
I've been meaning to get around to this. For me the MIT license is fine.

@boncey wrote most of the code though, so he has to approve. Do you have any objections against this license? If not I will publish a LICENSE file in the repository.

**Comment by antoneliasson** [comment]
I also sent an e-mail to Stefan Krupop who has also contributed. But that's all of us, so it shouldn't be too hard to agree on a license retroactively.

**Comment by boncey** [comment]
Fine by me!

**Comment by antoneliasson** [comment]
Stefan Krupop has also approved. I have pushed LICENSE files to this repository and lcdjava-demos. Do please tell us about your commercial product if you are able to. Either open an issue or write on the lcdproc mailing list. Have a nice day!

**Comment by manitou2k** [comment]
Thanks Gents!  I appreciate it. 

I will let you know about the project once I can - a bit early at the moment.

Barry
